# Site settings
author: Taylor Ishimoto
title: Journey to becoming a Software Engineering
header-img: img/home-bg.png
email: kikuish@gmail.com
copyright_name: Taylor Ishimoto
description: > # this means to ignore newlines until "baseurl:"
  Follow along as I document the process of becoming a Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kikuishimoto

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
